#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x17A6D3FF338C9570 (gedakc@gmail.com)
#
Name     : gparted
Version  : 0.33.0
Release  : 1
URL      : https://downloads.sourceforge.net/project/gparted/gparted/gparted-0.33.0/gparted-0.33.0.tar.gz
Source0  : https://downloads.sourceforge.net/project/gparted/gparted/gparted-0.33.0/gparted-0.33.0.tar.gz
Source99 : https://downloads.sourceforge.net/project/gparted/gparted/gparted-0.33.0/gparted-0.33.0.tar.gz.sig
Summary  : A Partition Magic clone, frontend to GNU Parted
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: gparted-bin = %{version}-%{release}
Requires: gparted-data = %{version}-%{release}
Requires: gparted-license = %{version}-%{release}
Requires: gparted-locales = %{version}-%{release}
Requires: gparted-man = %{version}-%{release}
BuildRequires : gettext
BuildRequires : gnome-doc-utils
BuildRequires : intltool
BuildRequires : parted-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(glibmm-2.4)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtkmm-2.4)
BuildRequires : pkgconfig(libparted)
BuildRequires : pkgconfig(sigc++-2.0)

%description
GPARTED
=======
Gparted is the GNOME Partition Editor for creating, reorganizing, and
deleting disk partitions.

%package bin
Summary: bin components for the gparted package.
Group: Binaries
Requires: gparted-data = %{version}-%{release}
Requires: gparted-license = %{version}-%{release}

%description bin
bin components for the gparted package.


%package data
Summary: data components for the gparted package.
Group: Data

%description data
data components for the gparted package.


%package license
Summary: license components for the gparted package.
Group: Default

%description license
license components for the gparted package.


%package locales
Summary: locales components for the gparted package.
Group: Default

%description locales
locales components for the gparted package.


%package man
Summary: man components for the gparted package.
Group: Default

%description man
man components for the gparted package.


%prep
%setup -q -n gparted-0.33.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551462381
%configure --disable-static --disable-doc
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1551462381
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gparted
cp COPYING %{buildroot}/usr/share/package-licenses/gparted/COPYING
cp lib/gtest/LICENSE %{buildroot}/usr/share/package-licenses/gparted/lib_gtest_LICENSE
%make_install
%find_lang gparted

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gparted
/usr/bin/gpartedbin

%files data
%defattr(-,root,root,-)
/usr/share/appdata/gparted.appdata.xml
/usr/share/applications/gparted.desktop
/usr/share/icons/hicolor/16x16/apps/gparted.png
/usr/share/icons/hicolor/22x22/apps/gparted.png
/usr/share/icons/hicolor/24x24/apps/gparted.png
/usr/share/icons/hicolor/32x32/apps/gparted.png
/usr/share/icons/hicolor/48x48/apps/gparted.png
/usr/share/icons/hicolor/scalable/apps/gparted.svg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gparted/COPYING
/usr/share/package-licenses/gparted/lib_gtest_LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/gparted.8

%files locales -f gparted.lang
%defattr(-,root,root,-)

